[2025-06-16T16:06:54.484+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-16T16:06:54.513+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_shot_chart_and_load_to_postgres manual__2025-06-16T16:06:49.836714+00:00 [queued]>
[2025-06-16T16:06:54.668+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_shot_chart_and_load_to_postgres manual__2025-06-16T16:06:49.836714+00:00 [queued]>
[2025-06-16T16:06:54.668+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-16T16:06:54.719+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_shot_chart_and_load_to_postgres> on 2025-06-16 16:06:49.836714+00:00
[2025-06-16T16:06:54.726+0000] {standard_task_runner.py:63} INFO - Started process 4936 to run task
[2025-06-16T16:06:54.730+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_postgres', 'fetch_shot_chart_and_load_to_postgres', 'manual__2025-06-16T16:06:49.836714+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpguioqzbs']
[2025-06-16T16:06:54.731+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask fetch_shot_chart_and_load_to_postgres
[2025-06-16T16:06:54.809+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_postgres.fetch_shot_chart_and_load_to_postgres manual__2025-06-16T16:06:49.836714+00:00 [running]> on host 11d91b3c2b82
[2025-06-16T16:06:54.958+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_shot_chart_and_load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T16:06:49.836714+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T16:06:49.836714+00:00'
[2025-06-16T16:06:54.959+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-16T16:06:54.983+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/etl_pipeline.py:150 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T16:06:59.260+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-22 between BOS and NYK.
[2025-06-16T16:07:06.189+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-22 between LAL and MIN.
[2025-06-16T16:07:13.593+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between DET and IND.
[2025-06-16T16:07:20.471+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between ATL and BRK.
[2025-06-16T16:07:26.849+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between MIA and ORL.
[2025-06-16T16:07:33.588+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between PHI and MIL.
[2025-06-16T16:07:40.490+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between TOR and CLE.
[2025-06-16T16:07:47.322+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between HOU and CHO.
[2025-06-16T16:07:53.824+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between NOP and CHI.
[2025-06-16T16:08:00.485+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between UTA and MEM.
[2025-06-16T16:08:07.130+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between LAC and PHO.
[2025-06-16T16:08:14.192+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between POR and GSW.
[2025-06-16T16:08:21.132+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-24 between WAS and BOS.
[2025-06-16T16:08:27.711+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-24 between DAL and SAS.
[2025-06-16T16:08:34.384+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-24 between DEN and OKC.
[2025-06-16T16:08:41.175+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-24 between SAC and MIN.
[2025-06-16T16:08:48.098+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-25 between ORL and BRK.
[2025-06-16T16:08:54.732+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-25 between TOR and PHI.
[2025-06-16T16:09:01.506+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-25 between ATL and CHO.
[2025-06-16T16:09:08.444+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-25 between CLE and DET.
[2025-06-16T16:09:08.452+0000] {logging_mixin.py:188} INFO - Ensuring table 'stgshotchart' exists...
[2025-06-16T16:09:08.454+0000] {logging_mixin.py:188} INFO - Table 'stgshotchart' is ready.
[2025-06-16T16:09:08.454+0000] {logging_mixin.py:188} INFO - Truncating table stgshotchart...
[2025-06-16T16:09:08.461+0000] {logging_mixin.py:188} INFO - Loading 3507 rows into stgshotchart...
[2025-06-16T16:09:08.520+0000] {logging_mixin.py:188} INFO - Database execution error: integer out of range
[2025-06-16T16:09:08.521+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-16T16:09:08.521+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 173, in fetch_and_load_shot_chart_to_stage
    load_df_to_postgres(df=final_df, table_name=table_name, conn_string=conn_string, create_table_query=create_table_query)
  File "/opt/airflow/dags/etl_pipeline.py", line 66, in load_df_to_postgres
    execute_values(cursor, sql_query, data_tuples)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.NumericValueOutOfRange: integer out of range

[2025-06-16T16:09:08.538+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_etl_to_postgres, task_id=fetch_shot_chart_and_load_to_postgres, run_id=manual__2025-06-16T16:06:49.836714+00:00, execution_date=20250616T160649, start_date=20250616T160654, end_date=20250616T160908
[2025-06-16T16:09:08.632+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task fetch_shot_chart_and_load_to_postgres (integer out of range
; 4936)
[2025-06-16T16:09:08.675+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-16T16:09:08.697+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-16T16:09:08.728+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
