[2025-06-15T21:53:33.897+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T21:53:33.931+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_staging_to_dwh.transform_load_dim_match manual__2025-06-15T21:53:31.717251+00:00 [queued]>
[2025-06-15T21:53:33.941+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_staging_to_dwh.transform_load_dim_match manual__2025-06-15T21:53:31.717251+00:00 [queued]>
[2025-06-15T21:53:33.942+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-15T21:53:33.990+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_dim_match> on 2025-06-15 21:53:31.717251+00:00
[2025-06-15T21:53:33.998+0000] {standard_task_runner.py:63} INFO - Started process 920 to run task
[2025-06-15T21:53:34.004+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_staging_to_dwh', 'transform_load_dim_match', 'manual__2025-06-15T21:53:31.717251+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpacat_67k']
[2025-06-15T21:53:34.005+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask transform_load_dim_match
[2025-06-15T21:53:34.137+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_staging_to_dwh.transform_load_dim_match manual__2025-06-15T21:53:31.717251+00:00 [running]> on host 11d91b3c2b82
[2025-06-15T21:53:34.295+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_staging_to_dwh' AIRFLOW_CTX_TASK_ID='transform_load_dim_match' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T21:53:31.717251+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-15T21:53:31.717251+00:00'
[2025-06-15T21:53:34.296+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T21:53:34.333+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/etl_pipeline.py:312 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T21:53:34.358+0000] {logging_mixin.py:188} INFO - Ensuring table 'dimmatch' exists...
[2025-06-15T21:53:34.477+0000] {logging_mixin.py:188} INFO - Table 'dimmatch' is ready.
[2025-06-15T21:53:34.483+0000] {logging_mixin.py:188} INFO - Loading 1321 rows into dimmatch...
[2025-06-15T21:53:34.545+0000] {logging_mixin.py:188} INFO - 1321 rows loaded successfully to dimmatch.
[2025-06-15T21:53:34.604+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-15T21:53:34.608+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T21:53:34.628+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nba_staging_to_dwh, task_id=transform_load_dim_match, run_id=manual__2025-06-15T21:53:31.717251+00:00, execution_date=20250615T215331, start_date=20250615T215333, end_date=20250615T215334
[2025-06-15T21:53:34.700+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-15T21:53:34.731+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-15T21:53:34.766+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
