[2025-06-15T21:55:07.516+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T21:55:07.660+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_shot_chart_and_load_to_postgres manual__2025-06-15T21:55:01.894822+00:00 [queued]>
[2025-06-15T21:55:07.713+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_shot_chart_and_load_to_postgres manual__2025-06-15T21:55:01.894822+00:00 [queued]>
[2025-06-15T21:55:07.715+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-15T21:55:07.812+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_shot_chart_and_load_to_postgres> on 2025-06-15 21:55:01.894822+00:00
[2025-06-15T21:55:07.834+0000] {standard_task_runner.py:63} INFO - Started process 948 to run task
[2025-06-15T21:55:07.848+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_postgres', 'fetch_shot_chart_and_load_to_postgres', 'manual__2025-06-15T21:55:01.894822+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpb7rkpzyj']
[2025-06-15T21:55:07.852+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask fetch_shot_chart_and_load_to_postgres
[2025-06-15T21:55:08.006+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_postgres.fetch_shot_chart_and_load_to_postgres manual__2025-06-15T21:55:01.894822+00:00 [running]> on host 11d91b3c2b82
[2025-06-15T21:55:08.157+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_shot_chart_and_load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T21:55:01.894822+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-15T21:55:01.894822+00:00'
[2025-06-15T21:55:08.159+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T21:55:08.189+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/etl_pipeline.py:147 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T21:55:44.847+0000] {logging_mixin.py:188} INFO - Retrying after 3600 sec...
[2025-06-15T22:56:01.926+0000] {logging_mixin.py:188} INFO - Retrying after 3600 sec...
[2025-06-15T23:56:20.880+0000] {logging_mixin.py:188} INFO - Retrying after 3600 sec...
[2025-06-16T00:56:41.393+0000] {logging_mixin.py:188} INFO - Retrying after 3600 sec...
[2025-06-16T01:57:02.597+0000] {logging_mixin.py:188} INFO - Retrying after 3600 sec...
[2025-06-16T02:57:38.941+0000] {logging_mixin.py:188} INFO - Retrying after 3600 sec...
[2025-06-16T03:59:06.920+0000] {logging_mixin.py:188} INFO - Retrying after 3600 sec...
[2025-06-16T05:00:44.149+0000] {logging_mixin.py:188} INFO - Retrying after 3600 sec...
[2025-06-16T06:02:27.551+0000] {logging_mixin.py:188} INFO - Retrying after 3600 sec...
[2025-06-16T06:25:46.520+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-06-16T06:25:46.522+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-16T06:25:46.525+0000] {process_utils.py:132} INFO - Sending 15 to group 948. PIDs of all processes in the group: [948]
[2025-06-16T06:25:46.526+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 948
[2025-06-16T06:25:46.526+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-16T06:25:46.527+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-16T06:25:46.659+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=948, status='terminated', exitcode=0, started='21:55:07') (948) terminated with exit code 0
