[2025-06-19T09:31:58.605+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-19T09:31:58.644+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_shot_chart_and_load_to_postgres manual__2025-06-19T09:16:58.571124+00:00 [queued]>
[2025-06-19T09:31:58.823+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_shot_chart_and_load_to_postgres manual__2025-06-19T09:16:58.571124+00:00 [queued]>
[2025-06-19T09:31:58.824+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-19T09:31:58.879+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_shot_chart_and_load_to_postgres> on 2025-06-19 09:16:58.571124+00:00
[2025-06-19T09:31:58.887+0000] {standard_task_runner.py:63} INFO - Started process 1224 to run task
[2025-06-19T09:31:58.892+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_postgres', 'fetch_shot_chart_and_load_to_postgres', 'manual__2025-06-19T09:16:58.571124+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpd_slk38q']
[2025-06-19T09:31:58.893+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask fetch_shot_chart_and_load_to_postgres
[2025-06-19T09:31:58.990+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_postgres.fetch_shot_chart_and_load_to_postgres manual__2025-06-19T09:16:58.571124+00:00 [running]> on host 11d91b3c2b82
[2025-06-19T09:31:59.163+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_shot_chart_and_load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T09:16:58.571124+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T09:16:58.571124+00:00'
[2025-06-19T09:31:59.165+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-19T09:31:59.192+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/etl_pipeline.py:158 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-19T09:32:03.541+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-22 between BOS and NYK.
[2025-06-19T09:32:10.475+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-22 between LAL and MIN.
[2025-06-19T09:32:17.579+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between DET and IND.
[2025-06-19T09:32:23.456+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between ATL and BRK.
[2025-06-19T09:32:30.659+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between MIA and ORL.
[2025-06-19T09:32:37.640+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between PHI and MIL.
[2025-06-19T09:32:44.552+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between TOR and CLE.
[2025-06-19T09:32:50.260+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between HOU and CHO.
[2025-06-19T09:32:57.111+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between NOP and CHI.
[2025-06-19T09:33:03.935+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between UTA and MEM.
[2025-06-19T09:33:10.829+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between LAC and PHO.
[2025-06-19T09:33:18.113+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-23 between POR and GSW.
[2025-06-19T09:33:24.196+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-24 between WAS and BOS.
[2025-06-19T09:33:31.159+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-24 between DAL and SAS.
[2025-06-19T09:33:38.024+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-24 between DEN and OKC.
[2025-06-19T09:33:45.085+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-24 between SAC and MIN.
[2025-06-19T09:33:50.813+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-25 between ORL and BRK.
[2025-06-19T09:33:58.035+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-25 between TOR and PHI.
[2025-06-19T09:34:04.885+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-25 between ATL and CHO.
[2025-06-19T09:34:11.735+0000] {logging_mixin.py:188} INFO - Processed game on 2024-10-25 between CLE and DET.
[2025-06-19T09:34:11.743+0000] {logging_mixin.py:188} INFO - Ensuring table 'stgshotchart' exists...
[2025-06-19T09:34:11.744+0000] {logging_mixin.py:188} INFO - Table 'stgshotchart' is ready.
[2025-06-19T09:34:11.745+0000] {logging_mixin.py:188} INFO - Truncating table stgshotchart...
[2025-06-19T09:34:11.752+0000] {logging_mixin.py:188} INFO - Loading 3507 rows into stgshotchart...
[2025-06-19T09:34:11.813+0000] {logging_mixin.py:188} INFO - Database execution error: integer out of range
[2025-06-19T09:34:11.814+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-19T09:34:11.815+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 181, in fetch_and_load_shot_chart_to_stage
    load_df_to_postgres(df=final_df, table_name=table_name, conn_string=conn_string, create_table_query=create_table_query)
  File "/opt/airflow/dags/etl_pipeline.py", line 66, in load_df_to_postgres
    execute_values(cursor, sql_query, data_tuples)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.NumericValueOutOfRange: integer out of range

[2025-06-19T09:34:11.829+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_etl_to_postgres, task_id=fetch_shot_chart_and_load_to_postgres, run_id=manual__2025-06-19T09:16:58.571124+00:00, execution_date=20250619T091658, start_date=20250619T093158, end_date=20250619T093411
[2025-06-19T09:34:11.883+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 83 for task fetch_shot_chart_and_load_to_postgres (integer out of range
; 1224)
[2025-06-19T09:34:11.903+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-19T09:34:11.923+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T09:34:11.955+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
