[2025-06-15T20:38:11.192+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T20:38:11.223+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-15T20:38:11.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-15T20:38:11.232+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-15T20:38:11.323+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_load_teams_to_stage> on 2025-06-08 00:00:00+00:00
[2025-06-15T20:38:11.340+0000] {standard_task_runner.py:63} INFO - Started process 864 to run task
[2025-06-15T20:38:11.347+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_postgres', 'fetch_and_load_teams_to_stage', 'scheduled__2025-06-08T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpy3pryn5z']
[2025-06-15T20:38:11.349+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask fetch_and_load_teams_to_stage
[2025-06-15T20:38:11.463+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [running]> on host 1c61638087f1
[2025-06-15T20:38:12.116+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_and_load_teams_to_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T00:00:00+00:00'
[2025-06-15T20:38:12.118+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T20:38:14.168+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T20:38:14.169+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 283, in fetch_and_load_teams_to_stage
    cur.copy_expert(sql_copy_command, f)
psycopg2.errors.UndefinedTable: relation "stgteam" does not exist

[2025-06-15T20:38:14.183+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_etl_to_postgres, task_id=fetch_and_load_teams_to_stage, run_id=scheduled__2025-06-08T00:00:00+00:00, execution_date=20250608T000000, start_date=20250615T203811, end_date=20250615T203814
[2025-06-15T20:38:14.273+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task fetch_and_load_teams_to_stage (relation "stgteam" does not exist
; 864)
[2025-06-15T20:38:14.345+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-15T20:38:14.357+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-15T20:39:17.621+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T20:39:17.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-15T20:39:17.657+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-15T20:39:17.658+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-15T20:39:17.691+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_load_teams_to_stage> on 2025-06-08 00:00:00+00:00
[2025-06-15T20:39:17.698+0000] {standard_task_runner.py:63} INFO - Started process 898 to run task
[2025-06-15T20:39:17.701+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_postgres', 'fetch_and_load_teams_to_stage', 'scheduled__2025-06-08T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp302z3_a2']
[2025-06-15T20:39:17.702+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask fetch_and_load_teams_to_stage
[2025-06-15T20:39:17.791+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [running]> on host 1c61638087f1
[2025-06-15T20:39:17.972+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_and_load_teams_to_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T00:00:00+00:00'
[2025-06-15T20:39:17.974+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T20:39:17.994+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T20:39:17.995+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 283, in fetch_and_load_teams_to_stage
    cur.copy_expert(sql_copy_command, f)
psycopg2.errors.UndefinedTable: relation "stgteam" does not exist

[2025-06-15T20:39:18.009+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_etl_to_postgres, task_id=fetch_and_load_teams_to_stage, run_id=scheduled__2025-06-08T00:00:00+00:00, execution_date=20250608T000000, start_date=20250615T203917, end_date=20250615T203918
[2025-06-15T20:39:18.045+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task fetch_and_load_teams_to_stage (relation "stgteam" does not exist
; 898)
[2025-06-15T20:39:18.074+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-15T20:39:18.091+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-15T20:39:18.124+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-15T21:05:17.418+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T21:05:17.451+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-15T21:05:17.459+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [queued]>
[2025-06-15T21:05:17.459+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-15T21:05:17.500+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_load_teams_to_stage> on 2025-06-08 00:00:00+00:00
[2025-06-15T21:05:17.506+0000] {standard_task_runner.py:63} INFO - Started process 886 to run task
[2025-06-15T21:05:17.510+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_etl_to_postgres', 'fetch_and_load_teams_to_stage', 'scheduled__2025-06-08T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpm6neizy8']
[2025-06-15T21:05:17.511+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask fetch_and_load_teams_to_stage
[2025-06-15T21:05:17.631+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_etl_to_postgres.fetch_and_load_teams_to_stage scheduled__2025-06-08T00:00:00+00:00 [running]> on host 10d298296c8f
[2025-06-15T21:05:17.761+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_etl_to_postgres' AIRFLOW_CTX_TASK_ID='fetch_and_load_teams_to_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T00:00:00+00:00'
[2025-06-15T21:05:17.762+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T21:05:17.779+0000] {logging_mixin.py:188} INFO - Loading data from /opt/***/include/data/nba_teams_info_no_header.csv into stgteam...
[2025-06-15T21:05:17.807+0000] {logging_mixin.py:188} INFO - Data loaded successfully.
[2025-06-15T21:05:17.808+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-15T21:05:17.809+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T21:05:17.819+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nba_etl_to_postgres, task_id=fetch_and_load_teams_to_stage, run_id=scheduled__2025-06-08T00:00:00+00:00, execution_date=20250608T000000, start_date=20250615T210517, end_date=20250615T210517
[2025-06-15T21:05:17.884+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-15T21:05:17.901+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-15T21:05:17.934+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
