[2025-06-16T15:31:34.434+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-16T15:31:34.531+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_staging_to_dwh.transform_load_dim_match manual__2025-06-16T15:31:32.798448+00:00 [queued]>
[2025-06-16T15:31:34.973+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_staging_to_dwh.transform_load_dim_match manual__2025-06-16T15:31:32.798448+00:00 [queued]>
[2025-06-16T15:31:34.974+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-16T15:31:35.033+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_dim_match> on 2025-06-16 15:31:32.798448+00:00
[2025-06-16T15:31:35.047+0000] {standard_task_runner.py:63} INFO - Started process 4496 to run task
[2025-06-16T15:31:35.055+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_staging_to_dwh', 'transform_load_dim_match', 'manual__2025-06-16T15:31:32.798448+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpps_ba_b9']
[2025-06-16T15:31:35.058+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask transform_load_dim_match
[2025-06-16T15:31:35.273+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_staging_to_dwh.transform_load_dim_match manual__2025-06-16T15:31:32.798448+00:00 [running]> on host 11d91b3c2b82
[2025-06-16T15:31:35.697+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_staging_to_dwh' AIRFLOW_CTX_TASK_ID='transform_load_dim_match' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T15:31:32.798448+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T15:31:32.798448+00:00'
[2025-06-16T15:31:35.703+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-16T15:31:35.802+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/etl_pipeline.py:314 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T15:31:35.895+0000] {logging_mixin.py:188} INFO - Ensuring table 'dimmatch' exists...
[2025-06-16T15:31:35.900+0000] {logging_mixin.py:188} INFO - Table 'dimmatch' is ready.
[2025-06-16T15:31:35.924+0000] {logging_mixin.py:188} INFO - Loading 6605 rows into dimmatch...
[2025-06-16T15:31:36.303+0000] {logging_mixin.py:188} INFO - 6605 rows loaded successfully to dimmatch.
[2025-06-16T15:31:36.371+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-16T15:31:36.382+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-16T15:31:36.407+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nba_staging_to_dwh, task_id=transform_load_dim_match, run_id=manual__2025-06-16T15:31:32.798448+00:00, execution_date=20250616T153132, start_date=20250616T153134, end_date=20250616T153136
[2025-06-16T15:31:36.482+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-16T15:31:36.509+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-16T15:31:36.536+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
