[2025-06-21T12:05:58.920+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-21T12:05:59.173+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_transform_to_dwh.load_fc_shoot manual__2025-06-21T12:05:43.112004+00:00 [queued]>
[2025-06-21T12:05:59.185+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_transform_to_dwh.load_fc_shoot manual__2025-06-21T12:05:43.112004+00:00 [queued]>
[2025-06-21T12:05:59.186+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-21T12:05:59.234+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_fc_shoot> on 2025-06-21 12:05:43.112004+00:00
[2025-06-21T12:05:59.241+0000] {standard_task_runner.py:63} INFO - Started process 2270 to run task
[2025-06-21T12:05:59.245+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_transform_to_dwh', 'load_fc_shoot', 'manual__2025-06-21T12:05:43.112004+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpsnv90sct']
[2025-06-21T12:05:59.248+0000] {standard_task_runner.py:91} INFO - Job 415: Subtask load_fc_shoot
[2025-06-21T12:05:59.347+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_transform_to_dwh.load_fc_shoot manual__2025-06-21T12:05:43.112004+00:00 [running]> on host 5ea278fdf3a6
[2025-06-21T12:05:59.513+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nba_transform_to_dwh' AIRFLOW_CTX_TASK_ID='load_fc_shoot' AIRFLOW_CTX_EXECUTION_DATE='2025-06-21T12:05:43.112004+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-21T12:05:43.112004+00:00'
[2025-06-21T12:05:59.514+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-21T12:05:59.531+0000] {etl_pipeline.py:623} INFO - Ensuring fact table 'fcshoot' exists...
[2025-06-21T12:05:59.772+0000] {etl_pipeline.py:625} INFO - Loading/updating data into 'fcshoot'...
[2025-06-21T12:05:59.781+0000] {etl_pipeline.py:629} ERROR - Failed to create or load fact table 'fcshoot'. Error: column swz.team does not exist
LINE 37:     JOIN dimteam dt ON swz.team = dt.teamabv
                                ^

[2025-06-21T12:05:59.782+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-21T12:05:59.783+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 626, in create_fc_shoot
    cursor.execute(insert_query)
psycopg2.errors.UndefinedColumn: column swz.team does not exist
LINE 37:     JOIN dimteam dt ON swz.team = dt.teamabv
                                ^

[2025-06-21T12:05:59.801+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_transform_to_dwh, task_id=load_fc_shoot, run_id=manual__2025-06-21T12:05:43.112004+00:00, execution_date=20250621T120543, start_date=20250621T120559, end_date=20250621T120559
[2025-06-21T12:05:59.860+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 415 for task load_fc_shoot (column swz.team does not exist
LINE 37:     JOIN dimteam dt ON swz.team = dt.teamabv
                                ^
; 2270)
[2025-06-21T12:05:59.901+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-21T12:05:59.935+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-21T12:05:59.965+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
